networks:
  php_pro:
    driver: bridge

volumes:
  database_volume:
    driver: local

services:
  # Define the app service
  app:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    networks:
      - ${PROJECT_NETWORK}

  # Define the database service
  database:
    image: "mysql:8"
    ports:
      - "3606:3306"
    volumes:
      - "./databases:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - ${PROJECT_NETWORK}

  adminer:
      image: adminer
      restart: always
      ports:
        - "8084:8080"
      networks:
        - ${PROJECT_NETWORK}