CREATE DATABASE IF NOT EXISTS auto_park;
USE auto_park;

CREATE TABLE parks (id INT(11) PRIMARY KEY AUTO_INCREMENT, address VARCHAR(255) NOT NULL);

CREATE TABLE cars (id INT(11) PRIMARY KEY AUTO_INCREMENT, model VARCHAR(255) NOT NULL, price FLOAT NOT NULL, park_id INT(11) NOT NULL, FOREIGN KEY (park_id) REFERENCES parks(id));

CREATE TABLE drivers (id INT(11) PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL,  phone VARCHAR(255),  car_id INT(11) NOT NULL, FOREIGN KEY (car_id) REFERENCES cars(id));

CREATE TABLE customers (id INT(11) PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, phone VARCHAR(255));

CREATE TABLE orders (id INT(11) PRIMARY KEY AUTO_INCREMENT, start TEXT NOT NULL, finish TEXT NOT NULL, total FLOAT NOT NULL, driver_id INT(11) NOT NULL, customer_id INT(11) NOT NULL, FOREIGN KEY (driver_id) REFERENCES drivers(id), FOREIGN KEY (customer_id) REFERENCES customers(id));