CREATE TABLE IF NOT EXISTS leads_tasks(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
task_id INT UNSIGNED,
lead_id INT UNSIGNED,
FOREIGN KEY (task_id) REFERENCES tasks(id),
FOREIGN KEY (lead_id) REFERENCES leads(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;