CREATE TABLE IF NOT EXISTS leads (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) NOT NULL UNIQUE,
name VARCHAR(255) DEFAULT NULL,
city VARCHAR(255) DEFAULT NULL,
phone VARCHAR(255) DEFAULT NULL,
address VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;